-- DE: Neue Chat-/Diagnosetexte in allen zehn vorhandenen Locales; enUS bleibt Fallback.
-- EN: New chat/diagnostic strings in all ten existing locales; enUS remains the fallback.
local keys = {
    "Chat Announcements", "Chat Announcements help", "Emote", "Emote help", "Raid", "Raid help",
    "Custom channel blocked", "Chat Diagnostics", "Diagnostics help", "Record diagnostics",
    "Diagnostic targets help", "Test outside combat", "Test combat", "Test encounter", "Diagnostic tests help",
    "Test local frames", "Local frames help", "Cancel diagnostic test", "Clear diagnostic log", "Clear diagnostic log help",
    "Diagnostics enabled", "Diagnostics disabled", "Diagnostic log cleared", "Diagnostic test already running",
    "Diagnostic timer unavailable", "Diagnostic suite started", "Diagnostic suite expired", "Diagnostic suite finished",
    "Diagnostic test message", "Diagnostic test cancelled", "Diagnostic target saved", "Diagnostic receipt saved", "Diagnostic command help",
}
local commands = "\n/qa diag on|off|status|clear|cancel|frames\n/qa diag suite out|combat|encounter\n/qa diag whisper Name-Realm\n/qa diag channel ChannelName\n/qa diag received TEST-ID\n/qadiag ..."
local texts = {
    enUS = {
        "Chat announcements", "Enable sending to the selected chat channels below. This is the master switch, not a raid channel or a local-only chat display.",
        "Emote", "Send quest announcements as custom /emote text. Blizzard restrictions depend on the client and situation.",
        "Raid", "Send announcements to raid chat when you are in a raid group. Separate from the local raid warning display.",
        "Blizzard currently blocks automatic custom-channel messages in the tested Retail client. Other clients use their own restriction checks.",
        "Chat diagnostics", "Record actual chat decisions silently. No extra chat messages. Up to 2000 entries; saved by WoW on /reload or logout. Message text and recipient names are not recorded. Active tests are separate.",
        "Record diagnostics", "Optional test recipient and an already joined private test channel. These settings do not change your normal announcement targets. No automatic channel join.",
        "Test outside combat", "Test regular combat", "Test boss encounter", "Explicitly sends one test per eligible channel, at least 8 seconds apart. Waits for the selected context, expires after 5 minutes. Public messages are visible; Blizzard block errors may appear. Starts recording. No automatic restart after reload.",
        "Test local displays", "After 5 seconds, test the UI error display and the addon-owned raid notice. Local output only; does not send raid chat. Starts recording.",
        "Cancel test", "Clear diagnostic log", "Delete recorded entries only; preserve profiles, test targets and recording settings.",
        "Diagnostics enabled.", "Diagnostics disabled.", "Diagnostic log cleared.", "A diagnostic test is already running. Cancel it first.",
        "Required diagnostic timer or encounter API unavailable.", "Test series started; visible messages and blocked-action errors may occur.",
        "Test series expired; remaining channels were not tested.", "Test series finished. Use /reload to save the log.",
        "Automatic one-shot chat test.", "Diagnostic test cancelled.", "Diagnostic target saved.", "Manual receipt recorded while logging is enabled.",
        "Diagnostic commands (tokens are the same in every language):",
    },
    deDE = {
        "Chatankündigungen", "Aktiviert den Versand an die unten gewählten Chatkanäle. Dies ist der Hauptschalter, kein Schlachtzugkanal und keine rein lokale Chatanzeige.",
        "Emote", "Sendet Questmeldungen als eigenen /emote-Text. Blizzard-Beschränkungen hängen vom Client und der Situation ab.",
        "Schlachtzug", "Sendet in den Schlachtzugchat, wenn du einer Raidgruppe angehörst. Getrennt von der lokalen Schlachtzugswarnungsanzeige.",
        "Blizzard blockiert derzeit automatische Nachrichten in eigene Chatkanäle im getesteten Retail-Client. Andere Clients verwenden eigene Restriktionsprüfungen.",
        "Chatdiagnose", "Zeichnet echte Versandentscheidungen still auf, ohne zusätzliche Chatnachrichten. Bis zu 2000 Einträge; WoW speichert bei /reload oder Logout. Nachrichtentexte und Empfängernamen werden nicht protokolliert. Aktive Tests sind separat.",
        "Diagnose aufzeichnen", "Optionaler Testempfänger und ein bereits betretener eigener Testkanal. Diese Einstellungen ändern keine normalen Ausgabeziele. Kein automatischer Kanalbeitritt.",
        "Außerhalb des Kampfes testen", "Gewöhnlichen Kampf testen", "Bosskampf testen", "Sendet ausdrücklich einen Test je geeignetem Kanal mit mindestens 8 Sekunden Abstand. Wartet auf den gewählten Zustand; läuft nach 5 Minuten ab. Öffentliche Nachrichten sind sichtbar; Blizzard-Schutzfehler können erscheinen. Startet die Aufzeichnung. Kein Neustart nach Reload.",
        "Lokale Anzeigen testen", "Testet nach 5 Sekunden UI-Fehleranzeige und addon-eigenen Raid-Hinweis. Nur lokale Ausgabe, kein Raidchat. Startet die Aufzeichnung.",
        "Test abbrechen", "Diagnoselog löschen", "Löscht nur protokollierte Einträge; Profile, Testziele und Aufzeichnungseinstellung bleiben erhalten.",
        "Diagnose aktiviert.", "Diagnose deaktiviert.", "Diagnoselog gelöscht.", "Ein Diagnosetest läuft bereits. Zuerst abbrechen.",
        "Erforderlicher Diagnosetimer oder Encounter-API fehlt.", "Testserie gestartet; sichtbare Nachrichten und Schutzfehler sind möglich.",
        "Testserie abgelaufen; übrige Kanäle wurden nicht getestet.", "Testserie beendet. Mit /reload das Log speichern.",
        "Automatischer einmaliger Chattest.", "Diagnosetest abgebrochen.", "Diagnoseziel gespeichert.", "Manuelle Empfangsbestätigung bei aktiver Aufzeichnung protokolliert.",
        "Diagnosebefehle (Befehlswörter sind in allen Sprachen gleich):",
    },
    esES = {
        "Anuncios de chat", "Activa el envío a los canales seleccionados abajo. Es el interruptor principal, no un canal de banda ni una pantalla de chat solo local.",
        "Emoción", "Envía anuncios de misiones como texto personalizado de /emote. Las restricciones dependen del cliente y la situación.",
        "Banda", "Envía al chat de banda cuando perteneces a una banda. Es independiente del aviso local de banda.",
        "Blizzard bloquea actualmente los mensajes automáticos en canales personalizados en el cliente Retail probado. Otros clientes usan sus propias comprobaciones.",
        "Diagnóstico de chat", "Registra decisiones reales en silencio, sin mensajes adicionales. Hasta 2000 entradas; WoW guarda al usar /reload o cerrar sesión. No registra textos ni nombres de destinatarios. Las pruebas activas son independientes.",
        "Registrar diagnóstico", "Destinatario de prueba opcional y canal privado al que ya te hayas unido. No cambia los destinos normales ni se une automáticamente a canales.",
        "Probar fuera de combate", "Probar combate normal", "Probar encuentro con jefe", "Envía una prueba por canal válido, con al menos 8 segundos de separación. Espera al contexto elegido y caduca a los 5 minutos. Los mensajes públicos son visibles y pueden aparecer errores de bloqueo. Activa el registro. No se reinicia tras /reload.",
        "Probar avisos locales", "Tras 5 segundos, prueba el aviso de error de IU y el aviso de banda propio del addon. Solo salida local, sin chat de banda. Activa el registro.",
        "Cancelar prueba", "Borrar registro", "Borra solo las entradas; conserva perfiles, destinos de prueba y la configuración de registro.",
        "Diagnóstico activado.", "Diagnóstico desactivado.", "Registro borrado.", "Ya hay una prueba en curso. Cancélala primero.",
        "Falta el temporizador o la API de encuentros necesaria.", "Serie iniciada; pueden aparecer mensajes visibles y errores de bloqueo.",
        "Serie caducada; los canales restantes no se probaron.", "Serie terminada. Usa /reload para guardar el registro.",
        "Prueba automática de chat de un solo intento.", "Prueba cancelada.", "Destino de diagnóstico guardado.", "Confirmación manual registrada si el registro está activo.",
        "Comandos de diagnóstico (iguales en todos los idiomas):",
    },
    esMX = {
        "Anuncios de chat", "Activa el envío a los canales seleccionados abajo. Es el interruptor principal, no un canal de banda ni una ventana de chat solo local.",
        "Emoción", "Envía anuncios de misiones como texto personalizado de /emote. Las restricciones dependen del cliente y de la situación.",
        "Banda", "Envía al chat de banda cuando estás en una banda. Es independiente del aviso local de banda.",
        "Blizzard bloquea actualmente mensajes automáticos en canales personalizados en el cliente Retail probado. Otros clientes usan sus propias comprobaciones.",
        "Diagnóstico de chat", "Registra decisiones reales en silencio y sin mensajes adicionales. Hasta 2000 entradas; WoW guarda al usar /reload o cerrar sesión. No registra textos ni nombres de destinatarios. Las pruebas activas son independientes.",
        "Registrar diagnóstico", "Destinatario opcional y canal privado al que ya te hayas unido. No cambia los destinos normales ni se une automáticamente a canales.",
        "Probar fuera de combate", "Probar combate normal", "Probar encuentro con jefe", "Envía una prueba por canal válido, separadas por al menos 8 segundos. Espera al contexto elegido y vence a los 5 minutos. Los mensajes públicos son visibles y pueden aparecer errores de bloqueo. Activa el registro. No se reinicia tras /reload.",
        "Probar avisos locales", "Después de 5 segundos, prueba el aviso de error de IU y el aviso de banda del addon. Solo salida local, sin chat de banda. Activa el registro.",
        "Cancelar prueba", "Borrar registro", "Borra solo entradas; conserva perfiles, destinos de prueba y configuración de registro.",
        "Diagnóstico activado.", "Diagnóstico desactivado.", "Registro borrado.", "Ya hay una prueba activa. Cancélala primero.",
        "Falta el temporizador o la API de encuentros necesaria.", "Serie iniciada; pueden aparecer mensajes visibles y errores de bloqueo.",
        "La serie venció; los canales restantes no se probaron.", "Serie terminada. Usa /reload para guardar el registro.",
        "Prueba automática de chat de un solo intento.", "Prueba cancelada.", "Destino de diagnóstico guardado.", "Confirmación manual registrada cuando el registro está activo.",
        "Comandos de diagnóstico (iguales en todos los idiomas):",
    },
    frFR = {
        "Annonces de discussion", "Active l'envoi aux canaux sélectionnés ci-dessous. C'est l'interrupteur général, pas un canal de raid ni un affichage local uniquement.",
        "Émote", "Envoie les annonces de quête sous forme de texte /emote personnalisé. Les restrictions dépendent du client et du contexte.",
        "Raid", "Envoie dans le canal de raid si vous êtes dans un groupe de raid. Indépendant de l'affichage local d'avertissement.",
        "Blizzard bloque actuellement les messages automatiques dans les canaux personnalisés sur le client Retail testé. Les autres clients utilisent leurs propres vérifications.",
        "Diagnostic de discussion", "Enregistre silencieusement les décisions réelles, sans message supplémentaire. Jusqu'à 2000 entrées, sauvegardées par WoW après /reload ou déconnexion. Aucun texte ni nom de destinataire enregistré. Tests actifs séparés.",
        "Enregistrer le diagnostic", "Destinataire de test facultatif et canal privé déjà rejoint. Ne modifie pas les destinations normales et ne rejoint aucun canal automatiquement.",
        "Tester hors combat", "Tester un combat normal", "Tester une rencontre de boss", "Envoie un test par canal admissible, espacés d'au moins 8 secondes. Attend le contexte choisi, expire après 5 minutes. Messages publics visibles et erreurs de blocage possibles. Active l'enregistrement. Aucun redémarrage après /reload.",
        "Tester les affichages locaux", "Après 5 secondes, teste l'affichage d'erreur d'interface et l'avis de raid propre à l'addon. Affichage local uniquement, sans message de raid. Active l'enregistrement.",
        "Annuler le test", "Effacer le journal", "Efface uniquement les entrées ; conserve les profils, destinations de test et réglages d'enregistrement.",
        "Diagnostic activé.", "Diagnostic désactivé.", "Journal effacé.", "Un test est déjà en cours. Annulez-le d'abord.",
        "Minuterie ou API de rencontre requise indisponible.", "Série démarrée ; messages visibles et erreurs de blocage possibles.",
        "Série expirée ; les canaux restants n'ont pas été testés.", "Série terminée. Utilisez /reload pour sauvegarder le journal.",
        "Test automatique de discussion à tentative unique.", "Test annulé.", "Destination de diagnostic enregistrée.", "Réception manuelle consignée si l'enregistrement est actif.",
        "Commandes de diagnostic (identiques dans toutes les langues) :",
    },
    ptBR = {
        "Anúncios no chat", "Ativa o envio aos canais selecionados abaixo. É a opção principal, não um canal de raide nem uma exibição apenas local.",
        "Emote", "Envia anúncios de missões como texto personalizado de /emote. As restrições dependem do cliente e da situação.",
        "Raide", "Envia ao chat de raide quando você está em um grupo de raide. Separado do aviso local de raide.",
        "A Blizzard bloqueia atualmente mensagens automáticas em canais personalizados no cliente Retail testado. Outros clientes usam suas próprias verificações.",
        "Diagnóstico de chat", "Registra decisões reais silenciosamente, sem mensagens extras. Até 2000 entradas; o WoW salva ao usar /reload ou sair. Não registra textos nem nomes de destinatários. Testes ativos são separados.",
        "Registrar diagnóstico", "Destinatário opcional e canal privado de teste já acessado. Não altera os destinos normais nem entra automaticamente em canais.",
        "Testar fora de combate", "Testar combate normal", "Testar encontro de chefe", "Envia um teste por canal válido, com intervalo mínimo de 8 segundos. Aguarda o contexto escolhido e expira após 5 minutos. Mensagens públicas são visíveis e erros de bloqueio podem aparecer. Ativa o registro. Não reinicia após /reload.",
        "Testar avisos locais", "Após 5 segundos, testa o aviso de erro da interface e o aviso de raide do addon. Apenas local, sem chat de raide. Ativa o registro.",
        "Cancelar teste", "Limpar registro", "Apaga apenas as entradas; preserva perfis, destinos de teste e configurações de registro.",
        "Diagnóstico ativado.", "Diagnóstico desativado.", "Registro apagado.", "Já existe um teste em andamento. Cancele-o primeiro.",
        "Temporizador ou API de encontro necessária indisponível.", "Série iniciada; mensagens visíveis e erros de bloqueio podem ocorrer.",
        "Série expirada; os canais restantes não foram testados.", "Série concluída. Use /reload para salvar o registro.",
        "Teste automático de chat com uma tentativa.", "Teste cancelado.", "Destino de diagnóstico salvo.", "Recebimento manual registrado quando o registro está ativo.",
        "Comandos de diagnóstico (iguais em todos os idiomas):",
    },
    ruRU = {
        "Объявления в чате", "Включает отправку в выбранные ниже каналы. Это общий переключатель, а не канал рейда или только локальный вывод.",
        "Эмоция", "Отправляет сообщения о заданиях как произвольный текст /emote. Ограничения зависят от клиента и ситуации.",
        "Рейд", "Отправляет сообщения в чат рейда, если вы в рейдовой группе. Отдельно от локального предупреждения о рейде.",
        "Blizzard сейчас блокирует автоматические сообщения в собственные каналы в проверенном клиенте Retail. Другие клиенты используют отдельные проверки.",
        "Диагностика чата", "Тихо записывает реальные решения об отправке, без дополнительных сообщений. До 2000 записей; WoW сохраняет при /reload или выходе. Тексты и имена получателей не записываются. Активные тесты запускаются отдельно.",
        "Записывать диагностику", "Необязательный получатель и собственный тестовый канал, в который вы уже вошли. Обычные настройки не меняются. Автоматического входа в канал нет.",
        "Тест вне боя", "Тест обычного боя", "Тест боя с боссом", "По одному тесту на доступный канал с интервалом минимум 8 секунд. Ожидает нужный контекст, истекает через 5 минут. Сообщения видны, возможны ошибки блокировки. Включает запись. После /reload не возобновляется.",
        "Тест локальных окон", "Через 5 секунд проверяет окно ошибок интерфейса и собственное рейдовое уведомление аддона. Только локальный вывод, без чата рейда. Включает запись.",
        "Отменить тест", "Очистить журнал", "Удаляет только записи; сохраняет профили, тестовые цели и настройку записи.",
        "Диагностика включена.", "Диагностика выключена.", "Журнал очищен.", "Тест уже выполняется. Сначала отмените его.",
        "Нужный таймер или API боя с боссом недоступен.", "Серия начата; возможны видимые сообщения и ошибки блокировки.",
        "Время серии истекло; остальные каналы не проверены.", "Серия завершена. Используйте /reload для сохранения журнала.",
        "Автоматический однократный тест чата.", "Тест отменён.", "Тестовая цель сохранена.", "Подтверждение получения записано при включённой записи.",
        "Команды диагностики (одинаковы для всех языков):",
    },
    koKR = {
        "채팅 알림", "아래에서 선택한 채널로 전송합니다. 전체 전송 설정이며 공격대 채널이나 개인 채팅 표시가 아닙니다.",
        "감정 표현", "퀘스트 알림을 사용자 지정 /emote 글로 보냅니다. 제한은 클라이언트와 상황에 따라 다릅니다.",
        "공격대", "공격대에 있을 때 공격대 채팅으로 보냅니다. 개인 공격대 경보 표시와는 별개입니다.",
        "테스트한 Retail 클라이언트에서는 Blizzard가 사용자 지정 채널의 자동 메시지를 차단합니다. 다른 클라이언트는 별도의 제한 검사를 사용합니다.",
        "채팅 진단", "추가 메시지 없이 실제 전송 판단을 조용히 기록합니다. 최대 2000개이며 /reload 또는 로그아웃 시 저장됩니다. 메시지 내용과 수신자 이름은 기록하지 않습니다. 능동 테스트는 별도입니다.",
        "진단 기록", "선택 사항인 테스트 수신자와 이미 참가한 전용 테스트 채널입니다. 일반 알림 대상은 변경하지 않으며 채널에 자동 참가하지 않습니다.",
        "비전투 테스트", "일반 전투 테스트", "우두머리 전투 테스트", "사용 가능한 채널마다 한 번씩 최소 8초 간격으로 전송합니다. 선택한 상황을 기다리며 5분 후 만료됩니다. 공개 메시지와 차단 오류가 표시될 수 있습니다. 기록을 켭니다. /reload 후 자동 재시작하지 않습니다.",
        "개인 표시 테스트", "5초 후 UI 오류 표시와 애드온 공격대 알림을 테스트합니다. 개인 표시만 사용하며 공격대 채팅은 보내지 않습니다. 기록을 켭니다.",
        "테스트 취소", "진단 기록 삭제", "기록만 삭제합니다. 프로필, 테스트 대상 및 기록 설정은 유지합니다.",
        "진단을 켰습니다.", "진단을 껐습니다.", "진단 기록을 삭제했습니다.", "테스트가 이미 진행 중입니다. 먼저 취소하세요.",
        "필요한 타이머 또는 우두머리 API를 사용할 수 없습니다.", "테스트를 시작했습니다. 메시지와 차단 오류가 표시될 수 있습니다.",
        "테스트 시간이 만료되었습니다. 남은 채널은 테스트하지 않았습니다.", "테스트를 마쳤습니다. /reload로 기록을 저장하세요.",
        "자동 단일 채팅 테스트.", "진단 테스트를 취소했습니다.", "진단 대상을 저장했습니다.", "기록이 켜져 있을 때 수동 수신 확인을 기록합니다.",
        "진단 명령어 (모든 언어에서 동일):",
    },
    zhCN = {
        "聊天通告", "启用向下方所选频道发送消息。这是总开关，并非团队频道或仅本地聊天显示。",
        "表情", "以自定义 /emote 文字发送任务通告。限制取决于客户端和当前情况。",
        "团队", "加入团队时向团队聊天发送通告，与本地团队警报显示独立。",
        "在已测试的 Retail 客户端中，暴雪目前阻止自动向自定义频道发送消息。其他客户端使用各自的限制检查。",
        "聊天诊断", "静默记录实际发送决策，不产生额外消息。最多2000条；/reload或退出登录时保存。不记录消息内容和收件人姓名。主动测试另行启动。",
        "记录诊断", "可选测试收件人和已加入的专用测试频道。不修改正常通告目标，也不自动加入频道。",
        "非战斗测试", "普通战斗测试", "首领战测试", "每个可用频道测试一次，间隔至少8秒。等待所选状态，5分钟后过期。公共消息可见，可能出现暴雪阻止操作错误。开启记录，/reload后不自动重启。",
        "测试本地显示", "5秒后测试界面错误显示及插件自有团队提示。仅本地输出，不发送团队聊天。开启记录。",
        "取消测试", "清除诊断日志", "仅删除日志记录，保留配置、测试目标及记录设置。",
        "诊断已启用。", "诊断已停用。", "诊断日志已清除。", "测试正在进行，请先取消。",
        "所需计时器或首领战API不可用。", "测试已开始，可能出现可见消息和阻止操作错误。",
        "测试已过期，剩余频道未测试。", "测试已完成，请使用/reload保存日志。",
        "自动单次聊天测试。", "诊断测试已取消。", "诊断目标已保存。", "记录启用时保存手动收件确认。",
        "诊断命令（所有语言使用相同命令）：",
    },
    zhTW = {
        "聊天公告", "啟用向下方所選頻道傳送訊息。這是總開關，並非團隊頻道或僅本機聊天顯示。",
        "表情", "以自訂 /emote 文字傳送任務公告。限制取決於客戶端和當前情況。",
        "團隊", "加入團隊時向團隊聊天傳送公告，與本機團隊警報顯示獨立。",
        "在已測試的 Retail 客戶端中，暴雪目前阻止自動向自訂頻道傳送訊息。其他客戶端使用各自的限制檢查。",
        "聊天診斷", "安靜記錄實際傳送判斷，不產生額外訊息。最多2000筆；/reload或登出時儲存。不記錄訊息內容和收件人姓名。主動測試另行啟動。",
        "記錄診斷", "可選測試收件人和已加入的專用測試頻道。不修改正常公告目標，也不自動加入頻道。",
        "非戰鬥測試", "一般戰鬥測試", "首領戰測試", "每個可用頻道測試一次，間隔至少8秒。等待所選狀態，5分鐘後到期。公開訊息可見，可能出現暴雪阻止操作錯誤。開啟記錄，/reload後不自動重啟。",
        "測試本機顯示", "5秒後測試介面錯誤顯示及插件自有團隊提示。僅本機輸出，不傳送團隊聊天。開啟記錄。",
        "取消測試", "清除診斷記錄", "僅刪除記錄，保留設定檔、測試目標及記錄設定。",
        "診斷已啟用。", "診斷已停用。", "診斷記錄已清除。", "測試正在進行，請先取消。",
        "所需計時器或首領戰API無法使用。", "測試已開始，可能出現可見訊息和阻止操作錯誤。",
        "測試已到期，其餘頻道未測試。", "測試已完成，請使用/reload儲存記錄。",
        "自動單次聊天測試。", "診斷測試已取消。", "診斷目標已儲存。", "記錄啟用時儲存手動收件確認。",
        "診斷命令（所有語言使用相同命令）：",
    },
}
for locale, values in pairs(texts) do
    local target = QuestAnnounce_L[locale]
    for i, key in ipairs(keys) do target[key]=values[i] end
    target["Diagnostic command help"]=target["Diagnostic command help"] .. commands
end
