-- DE: Partnerdiagnose in allen unterstützten Sprachen; Protokollwörter bleiben sprachunabhängig.
-- EN: Peer diagnostics in every supported locale; protocol tokens remain language-independent.
local keys={
    "Diagnostic partner", "Diagnostic partner help", "Diagnostic receive", "Diagnostic receive help",
    "Diagnostic partner required", "Diagnostic partner unavailable", "Diagnostic partner ready",
    "Diagnostic channels", "Diagnostic channels help", "Diagnostic channels required",
    "Diagnostic results", "Diagnostic results help", "Diagnostic confirm", "Diagnostic confirm help",
    "Diagnostic receiver on", "Diagnostic receiver off", "Diagnostic select result",
    "Diagnostic status waiting", "Diagnostic status pending", "Diagnostic status received", "Diagnostic status manual",
    "Diagnostic status skipped", "Diagnostic status blocked", "Diagnostic status error", "Diagnostic status unconfirmed",
    "Diagnostic status cancelled", "Diagnostic status local",
}
local texts={
    enUS={
        "Test partner (Name-Realm)", "Both players choose each other here. The recipient enables receiving. Leave blank for manual tests. In paired tests, WHISPER targets this partner. Normal quest settings stay unchanged.",
        "Receive partner tests", "Explicitly accept diagnostic tests only from the selected partner. Confirms actual chat events, not reading or window visibility. Test messages remain visible; acknowledgements use hidden addon communication.",
        "Choose a valid other character as test partner first.", "Partner connection unavailable or timed out. Enable receiving on the partner. No paired chat probes were sent; manual tests remain available.",
        "Partner ready. Waiting for the selected test context.", "Channels to test", "Select only the channels you need. Missing membership or targets are skipped. Both players need access; local chat also needs range. Start boss tests before the encounter to prepare the connection.",
        "Select at least one diagnostic channel.", "Recent results", "Partner receipt means a chat event reached the other client. Missing acknowledgement stays unconfirmed. Blocked replies are buffered for up to 10 minutes, including reload. Both clients keep receipt evidence; /reload saves the log.",
        "Confirm selected result", "For local displays or a partner without automatic acknowledgement: select a test below and confirm only after observing the display or checking with the recipient. No test-ID typing needed.",
        "Partner receiver enabled", "Partner receiver disabled", "Select a test for manual confirmation",
        "Waiting", "Confirmation pending", "Received by partner", "Manually confirmed", "Skipped", "Blizzard blocked", "API error", "Unconfirmed", "Cancelled", "Check local display",
    },
    deDE={
        "Testpartner (Name-Realm)", "Beide Spieler tragen sich hier gegenseitig ein. Der Empfänger aktiviert den Empfang. Für manuelle Tests leer lassen. WHISPER geht bei Partnertests an diesen Spieler. Normale Questoptionen bleiben erhalten.",
        "Partnertests empfangen", "Nimmt Diagnosetests ausdrücklich nur vom gewählten Partner an. Bestätigt tatsächliche Chatereignisse, nicht Lesen oder Sichtbarkeit im Fenster. Testnachrichten bleiben sichtbar; Rückmeldungen nutzen unsichtbare Addon-Kommunikation.",
        "Wähle zuerst einen gültigen anderen Charakter als Testpartner.", "Partnerverbindung fehlt oder ist abgelaufen. Beim Partner den Empfang aktivieren. Keine Partner-Chattests gesendet; manuelle Tests bleiben verfügbar.",
        "Partner bereit. Warte auf den gewählten Testzustand.", "Zu testende Kanäle", "Wähle nur benötigte Kanäle. Fehlende Zugehörigkeit oder Ziele werden übersprungen. Beide brauchen Zugang; lokaler Chat auch Reichweite. Bosstests vor dem Encounter starten, damit die Verbindung vorbereitet wird.",
        "Wähle mindestens einen Diagnosekanal.", "Letzte Ergebnisse", "Partnerempfang bedeutet ein Chatereignis beim anderen Client. Fehlende Rückmeldung bleibt unbestätigt. Gesperrte Rückmeldungen warten bis zu 10 Minuten, auch über Reload. Beide Clients speichern Empfangsbelege; /reload sichert das Log.",
        "Gewähltes Ergebnis bestätigen", "Für lokale Anzeigen oder Partner ohne automatische Rückmeldung: unten einen Test wählen und erst nach Sichtprüfung oder Rückfrage beim Empfänger bestätigen. Kein Abtippen von Test-IDs nötig.",
        "Partnerempfang aktiviert", "Partnerempfang deaktiviert", "Test zur manuellen Bestätigung wählen",
        "Wartet", "Bestätigung ausstehend", "Beim Partner empfangen", "Manuell bestätigt", "Übersprungen", "Von Blizzard blockiert", "API-Fehler", "Unbestätigt", "Abgebrochen", "Lokale Anzeige prüfen",
    },
    esES={
        "Compañero (Nombre-Reino)", "Ambos jugadores se seleccionan mutuamente. El destinatario activa la recepción. Déjalo vacío para pruebas manuales. WHISPER se dirige al compañero. No cambia los anuncios normales.",
        "Recibir pruebas del compañero", "Acepta pruebas solo del compañero elegido. Confirma eventos de chat, no la lectura ni la visibilidad. Las pruebas son visibles; las confirmaciones usan comunicación oculta del addon.",
        "Selecciona primero otro personaje válido.", "Conexión no disponible o caducada. Activa la recepción en el compañero. No se enviaron pruebas de chat emparejadas; siguen disponibles las manuales.",
        "Compañero listo. Esperando el contexto elegido.", "Canales de prueba", "Selecciona los canales necesarios. Se omiten los que no tengan requisitos. Ambos necesitan acceso y alcance para el chat local. Inicia pruebas de jefe antes del encuentro.",
        "Selecciona al menos un canal.", "Resultados recientes", "Recepción indica un evento de chat en el otro cliente. Sin confirmación queda sin verificar. Respuestas bloqueadas esperan hasta 10 minutos, incluso tras /reload. Ambos guardan evidencias; /reload guarda el registro.",
        "Confirmar resultado elegido", "Para avisos locales o recepción manual: selecciona una prueba y confirma tras verla o consultar al destinatario. No necesitas escribir IDs.",
        "Recepción activada", "Recepción desactivada", "Selecciona una prueba para confirmar",
        "Esperando", "Confirmación pendiente", "Recibido por compañero", "Confirmado manualmente", "Omitido", "Bloqueado por Blizzard", "Error de API", "Sin confirmar", "Cancelado", "Comprobar aviso local",
    },
    esMX={
        "Compañero (Nombre-Reino)", "Ambos jugadores se seleccionan mutuamente. El destinatario activa la recepción. Déjalo vacío para pruebas manuales. WHISPER va al compañero. No cambia los anuncios normales.",
        "Recibir pruebas del compañero", "Acepta pruebas solo del compañero seleccionado. Confirma eventos de chat, no lectura ni visibilidad. Las pruebas son visibles; las confirmaciones usan comunicación oculta del addon.",
        "Primero selecciona otro personaje válido.", "Conexión no disponible o vencida. Activa la recepción en el compañero. No se enviaron pruebas de chat emparejadas; puedes usar pruebas manuales.",
        "Compañero listo. Esperando el contexto seleccionado.", "Canales de prueba", "Selecciona los canales necesarios. Se omiten los que no cumplen los requisitos. Ambos necesitan acceso y alcance para el chat local. Inicia pruebas de jefe antes del encuentro.",
        "Selecciona al menos un canal.", "Resultados recientes", "Recepción indica un evento de chat en el otro cliente. Sin confirmación queda sin verificar. Respuestas bloqueadas esperan hasta 10 minutos, incluso tras /reload. Ambos guardan evidencias; /reload guarda el registro.",
        "Confirmar resultado seleccionado", "Para avisos locales o recepción manual: selecciona una prueba y confirma después de verla o preguntar al destinatario. No necesitas escribir IDs.",
        "Recepción activada", "Recepción desactivada", "Selecciona una prueba para confirmar",
        "Esperando", "Confirmación pendiente", "Recibido por compañero", "Confirmado manualmente", "Omitido", "Bloqueado por Blizzard", "Error de API", "Sin confirmar", "Cancelado", "Revisar aviso local",
    },
    frFR={
        "Partenaire (Nom-Royaume)", "Les deux joueurs se choisissent mutuellement. Le destinataire active la réception. Laissez vide pour les tests manuels. WHISPER vise ce partenaire. Les annonces normales restent inchangées.",
        "Recevoir les tests du partenaire", "Accepte uniquement le partenaire choisi. Confirme des événements de discussion, pas la lecture ni l'affichage. Les tests restent visibles ; les confirmations utilisent la communication cachée de l'addon.",
        "Choisissez d'abord un autre personnage valide.", "Connexion indisponible ou expirée. Activez la réception chez le partenaire. Aucun test de discussion apparié envoyé ; les tests manuels restent disponibles.",
        "Partenaire prêt. En attente du contexte choisi.", "Canaux à tester", "Choisissez les canaux nécessaires. Les prérequis manquants sont ignorés. Les deux joueurs doivent avoir accès et être à portée pour la discussion locale. Lancez les tests de boss avant le combat.",
        "Choisissez au moins un canal.", "Résultats récents", "La réception signifie un événement chez l'autre client. Sans confirmation, le résultat reste indéterminé. Les réponses bloquées attendent 10 minutes maximum, même après /reload. Les deux clients gardent des preuves ; /reload sauvegarde le journal.",
        "Confirmer le résultat choisi", "Pour l'affichage local ou la réception manuelle : choisissez un test et confirmez après vérification visuelle ou auprès du destinataire. Aucun identifiant à saisir.",
        "Réception activée", "Réception désactivée", "Choisir un test à confirmer",
        "En attente", "Confirmation en attente", "Reçu par le partenaire", "Confirmé manuellement", "Ignoré", "Bloqué par Blizzard", "Erreur API", "Non confirmé", "Annulé", "Vérifier l'affichage local",
    },
    ptBR={
        "Parceiro (Nome-Reino)", "Os dois jogadores selecionam um ao outro. O destinatário ativa a recepção. Deixe vazio para testes manuais. WHISPER vai para esse parceiro. Os anúncios normais não mudam.",
        "Receber testes do parceiro", "Aceita testes apenas do parceiro escolhido. Confirma eventos de bate-papo, não leitura ou visibilidade. Testes são visíveis; confirmações usam comunicação oculta do addon.",
        "Primeiro selecione outro personagem válido.", "Conexão indisponível ou expirada. Ative a recepção no parceiro. Nenhum teste de bate-papo em par foi enviado; testes manuais continuam disponíveis.",
        "Parceiro pronto. Aguardando o contexto escolhido.", "Canais para testar", "Escolha os canais necessários. Requisitos ausentes são ignorados. Ambos precisam de acesso e alcance no bate-papo local. Inicie testes de chefe antes do encontro.",
        "Escolha pelo menos um canal.", "Resultados recentes", "Recepção significa um evento no outro cliente. Sem confirmação, fica não confirmado. Respostas bloqueadas aguardam até 10 minutos, mesmo após /reload. Ambos guardam evidências; /reload salva o registro.",
        "Confirmar resultado escolhido", "Para avisos locais ou recepção manual: escolha um teste e confirme depois de ver o aviso ou consultar o destinatário. Não precisa digitar IDs.",
        "Recepção ativada", "Recepção desativada", "Escolha um teste para confirmar",
        "Aguardando", "Confirmação pendente", "Recebido pelo parceiro", "Confirmado manualmente", "Ignorado", "Bloqueado pela Blizzard", "Erro de API", "Não confirmado", "Cancelado", "Verificar aviso local",
    },
    ruRU={
        "Партнёр (Имя-Сервер)", "Оба игрока выбирают друг друга. Получатель включает приём. Оставьте пустым для ручных тестов. WHISPER отправляется партнёру. Обычные объявления не меняются.",
        "Принимать тесты партнёра", "Принимает тесты только выбранного партнёра. Подтверждает событие чата, а не прочтение или отображение. Тесты видимы; подтверждения используют скрытый канал аддона.",
        "Сначала выберите другого персонажа.", "Связь недоступна или время ожидания истекло. Включите приём у партнёра. Парные сообщения не отправлены; ручные тесты доступны.",
        "Партнёр готов. Ожидание выбранных условий.", "Каналы для теста", "Выберите нужные каналы. Без доступа или цели тест пропускается. Оба игрока должны иметь доступ, а для местного чата быть рядом. Запустите тест босса до боя.",
        "Выберите хотя бы один канал.", "Последние результаты", "Приём означает событие на другом клиенте. Без ответа результат не подтверждён. Заблокированные ответы ждут до 10 минут, включая /reload. Оба клиента хранят доказательства; /reload сохраняет журнал.",
        "Подтвердить выбранный результат", "Для местных окон или ручного приёма: выберите тест и подтвердите после проверки отображения или ответа получателя. Вводить ID не нужно.",
        "Приём включён", "Приём выключен", "Выберите тест для подтверждения",
        "Ожидание", "Ожидание подтверждения", "Получено партнёром", "Подтверждено вручную", "Пропущено", "Заблокировано Blizzard", "Ошибка API", "Не подтверждено", "Отменено", "Проверьте местное окно",
    },
    koKR={
        "테스트 상대 (이름-서버)", "두 플레이어가 서로를 선택합니다. 수신자는 수신을 켭니다. 수동 테스트는 비워 두세요. WHISPER는 이 상대에게 전송됩니다. 일반 알림 설정은 바뀌지 않습니다.",
        "상대 테스트 수신", "선택한 상대의 테스트만 받습니다. 읽음이나 창 표시가 아닌 실제 대화 이벤트를 확인합니다. 테스트 메시지는 보이며 확인은 숨겨진 애드온 통신을 사용합니다.",
        "먼저 다른 유효한 캐릭터를 선택하세요.", "상대 연결을 사용할 수 없거나 시간이 초과되었습니다. 상대의 수신을 켜세요. 연결 테스트 메시지는 전송되지 않았으며 수동 테스트는 가능합니다.",
        "상대가 준비되었습니다. 선택한 상황을 기다립니다.", "테스트 채널", "필요한 채널만 선택하세요. 조건이 부족하면 건너뜁니다. 양쪽 모두 접근 권한이 필요하며 지역 대화는 거리도 필요합니다. 우두머리 전투 전에 테스트를 시작하세요.",
        "채널을 하나 이상 선택하세요.", "최근 결과", "수신은 상대 클라이언트의 대화 이벤트를 뜻합니다. 응답이 없으면 미확인입니다. 차단된 응답은 /reload 후에도 최대 10분 기다립니다. 양쪽이 증거를 기록하며 /reload로 저장합니다.",
        "선택한 결과 확인", "개인 표시나 수동 수신 확인: 테스트를 선택하고 직접 표시를 보거나 수신자에게 확인한 뒤 누르세요. ID 입력은 필요 없습니다.",
        "상대 수신 켜짐", "상대 수신 꺼짐", "수동 확인할 테스트 선택",
        "대기", "확인 대기", "상대 수신 완료", "수동 확인 완료", "건너뜀", "블리자드 차단", "API 오류", "미확인", "취소됨", "개인 표시 확인 필요",
    },
    zhCN={
        "测试伙伴（名字-服务器）", "双方互相选择对方。收件人开启接收。手动测试请留空。WHISPER发送给此伙伴，不改变普通通告设置。",
        "接收伙伴测试", "只接受所选伙伴的测试。确认实际聊天事件，不代表已读或窗口显示。测试消息可见，确认使用隐藏的插件通信。",
        "请先选择一个有效的其他角色。", "伙伴连接不可用或超时。请在伙伴端开启接收。未发送配对聊天测试，仍可使用手动测试。",
        "伙伴已准备，等待所选测试状态。", "测试频道", "只选择需要的频道。缺少条件或目标时跳过。双方需有权限，本地聊天还需在范围内。首领测试应在战斗前启动以准备连接。",
        "请至少选择一个频道。", "最近结果", "伙伴接收表示对方客户端收到聊天事件。无回复保持未确认。被限制的回复最多等待10分钟，重载后仍保留。双方保存接收证据，/reload保存记录。",
        "确认所选结果", "本地显示或手动接收：选择测试，仅在看到显示或询问收件人后确认。无需输入测试ID。",
        "伙伴接收已开启", "伙伴接收已关闭", "选择需手动确认的测试",
        "等待中", "等待确认", "伙伴已接收", "已手动确认", "已跳过", "被暴雪阻止", "API错误", "未确认", "已取消", "请检查本地显示",
    },
    zhTW={
        "測試夥伴（名字-伺服器）", "雙方互相選擇對方。收件人開啟接收。手動測試請留空。WHISPER傳送給此夥伴，不改變一般通告設定。",
        "接收夥伴測試", "僅接受所選夥伴的測試。確認實際聊天事件，不代表已讀或視窗顯示。測試訊息可見，確認使用隱藏的插件通訊。",
        "請先選擇有效的其他角色。", "夥伴連線無法使用或逾時。請在夥伴端開啟接收。未傳送配對聊天測試，仍可使用手動測試。",
        "夥伴已準備，等待所選測試狀態。", "測試頻道", "僅選擇需要的頻道。缺少條件或目標時略過。雙方需有權限，本地聊天還需在範圍內。首領測試應在戰鬥前啟動以準備連線。",
        "請至少選擇一個頻道。", "最近結果", "夥伴接收表示對方用戶端收到聊天事件。無回覆保持未確認。受限制的回覆最多等待10分鐘，重載後仍保留。雙方保存接收證據，/reload儲存記錄。",
        "確認所選結果", "本地顯示或手動接收：選擇測試，僅在看到顯示或詢問收件人後確認。無需輸入測試ID。",
        "夥伴接收已開啟", "夥伴接收已關閉", "選擇需手動確認的測試",
        "等待中", "等待確認", "夥伴已接收", "已手動確認", "已略過", "被暴雪阻止", "API錯誤", "未確認", "已取消", "請檢查本地顯示",
    },
}
for locale, values in pairs(texts) do
    for index, key in ipairs(keys) do QuestAnnounce_L[locale][key]=values[index] end
    QuestAnnounce_L[locale]["Diagnostic command help"]=QuestAnnounce_L[locale]["Diagnostic command help"]
        .. "\n/qa diag partner Name-Realm\n/qa diag receive on|off\n/qa diag channels all|GUILD OFFICER"
end
local clearHelp={
    enUS="Stop active tests and clear log entries, results and pending receipts. Preserve profiles, diagnostic targets and recording settings.",
    deDE="Beendet aktive Tests und löscht Logeinträge, Ergebnisse und wartende Empfangsbestätigungen. Profile, Diagnoseziele und Aufzeichnungseinstellungen bleiben erhalten.",
    esES="Detiene las pruebas y borra entradas, resultados y confirmaciones pendientes. Conserva perfiles, destinos y configuración de registro.",
    esMX="Detiene las pruebas y borra registros, resultados y confirmaciones pendientes. Conserva perfiles, destinos y configuración de registro.",
    frFR="Arrête les tests et efface le journal, les résultats et les confirmations en attente. Conserve les profils, les destinations et les réglages d'enregistrement.",
    ptBR="Para os testes e apaga registros, resultados e confirmações pendentes. Preserva perfis, destinos e configurações de registro.",
    ruRU="Останавливает тесты и очищает журнал, результаты и ожидающие подтверждения. Сохраняет профили, цели и настройки записи.",
    koKR="테스트를 중지하고 기록, 결과 및 대기 중인 확인을 삭제합니다. 프로필, 진단 대상 및 기록 설정은 유지합니다.",
    zhCN="停止测试并清除日志、结果和待发送的接收确认。保留配置、诊断目标和记录设置。",
    zhTW="停止測試並清除日誌、結果及待傳送的接收確認。保留設定檔、診斷目標及記錄設定。",
}
for locale, text in pairs(clearHelp) do QuestAnnounce_L[locale]["Clear diagnostic log help"]=text end

-- DE: Aufbauphasen und Versandentscheidungen vollständig übersetzen, technische Loggründe bleiben stabil.
-- EN: Translate setup phases and routing decisions completely; technical log reasons remain stable.
local followupKeys={
    "Guild sending safety notice", "Raw restriction probes", "Raw restriction probes help",
    "Diagnostic setup failed", "Diagnostic build label", "Diagnostic preparation progress",
    "Diagnostic build mismatch", "Diagnostic starter guild recipient", "Diagnostic echo only",
    "Diagnostic phase idle", "Diagnostic phase searching", "Diagnostic phase preparing", "Diagnostic phase restricted",
    "Diagnostic phase ready", "Diagnostic phase testing", "Diagnostic phase finished", "Diagnostic phase cancelled",
    "Diagnostic reason unknown", "Diagnostic reason protected control action", "Diagnostic reason transport failed",
    "Diagnostic reason chat restriction setup timeout", "Diagnostic reason channel preparation timeout",
    "Diagnostic reason partner response timeout", "Diagnostic reason receiver disabled", "Diagnostic reason protocol mismatch",
    "Diagnostic reason guild automatic sending unverified", "Diagnostic reason previous protected send",
    "Diagnostic reason automatic public chat restriction", "Diagnostic reason automatic custom channel blocked",
    "Diagnostic reason player died", "Diagnostic reason log cleared", "Diagnostic reason no raid",
    "Diagnostic reason no home party", "Diagnostic reason no instance group", "Diagnostic reason no guild",
    "Diagnostic reason missing test recipient", "Diagnostic reason missing joined test channel", "Diagnostic reason no raid warning permission",
}
local followup={
    enUS={
        "Automatic guild sending is temporarily withheld on the measured Retail client: blocked calls also occurred without active Chat/Map restrictions. Your guild option is preserved; other destinations remain available.",
        "Probe Blizzard restrictions directly", "Off: test the addon's normal sending rules. On: make explicit one-shot API probes, including contexts the normal sender skips. Visible messages and Blizzard protection errors are possible. No restriction is bypassed. Wait for partner readiness before pulling a boss.",
        "Partner preparation stopped: %s", "Diagnostic build: %s", "Prepared channels: %d / %d",
        "Partner uses a different diagnostic build. Update both addons before comparing results.", "Starter recipient: guild/officer receipt cannot be verified with this partner.", "Own echo only; partner receipt is not confirmed.",
        "No active test", "Searching for partner", "Partner found; preparing channels", "Preparation waiting for chat restrictions to end", "Partner ready; waiting for test context", "Test running", "Test finished", "Test cancelled",
        "See the diagnostic log for details.", "Protected addon communication; no retry until reload.", "Addon communication failed.", "Preparation timed out while chat restrictions interrupted communication.", "Channel preparation did not finish within the time limit.", "No partner response within the time limit.", "The partner has not enabled receiving.", "Diagnostic protocol mismatch.",
        "Automatic guild sending is currently withheld for safety.", "This channel previously caused a protection error; no retry until reload.", "Automatic public chat is unavailable in this context.", "Automatic custom-channel sending is blocked on the measured Retail client.",
        "Player died.", "Diagnostic log cleared.", "No raid group.", "No home party.", "No instance group.", "Not in a guild.", "No test recipient configured.", "No joined test channel configured.", "No raid-warning permission.",
    },
    deDE={
        "Automatischer Gildenversand wird auf dem geprüften Retailclient vorübergehend zurückgehalten: Schutzfehler traten auch ohne aktive Chat-/Map-Sperre auf. Deine Gildenoption bleibt gespeichert; andere Ziele bleiben verfügbar.",
        "Blizzard-Restriktionen direkt prüfen", "Aus: normale Versandregeln des Addons testen. An: bewusst einzelne API-Aufrufe prüfen, auch in normalerweise übersprungenen Situationen. Sichtbare Nachrichten und Blizzard-Schutzfehler sind möglich. Keine Sperre wird umgangen. Vor dem Bosspull auf Partnerbereitschaft warten.",
        "Partnervorbereitung beendet: %s", "Diagnosebuild: %s", "Vorbereitete Kanäle: %d / %d",
        "Der Partner verwendet einen anderen Diagnosebuild. Beide Addons vor dem Ergebnisvergleich aktualisieren.", "Starter-Empfänger: Gilden-/Offizierempfang ist mit diesem Partner nicht überprüfbar.", "Nur eigener Chat-Echo; Partnerempfang nicht bestätigt.",
        "Kein aktiver Test", "Partner wird gesucht", "Partner erkannt; Kanäle werden vorbereitet", "Vorbereitung wartet auf das Ende der Chatsperre", "Partner bereit; wartet auf Testzustand", "Test läuft", "Test abgeschlossen", "Test abgebrochen",
        "Einzelheiten stehen im Diagnoseprotokoll.", "Addon-Kommunikation geschützt; kein erneuter Versuch bis Reload.", "Addon-Kommunikation fehlgeschlagen.", "Vorbereitung abgelaufen, während Chatsperren die Kommunikation unterbrachen.", "Kanalvorbereitung wurde nicht rechtzeitig abgeschlossen.", "Keine Partnerantwort innerhalb der Aufbaufrist.", "Der Partner hat den Empfang nicht aktiviert.", "Diagnoseprotokolle sind nicht kompatibel.",
        "Automatischer Gildenversand wird derzeit vorsorglich zurückgehalten.", "Dieser Kanal verursachte bereits einen Schutzfehler; kein erneuter Versuch bis Reload.", "Automatischer öffentlicher Chat ist in diesem Kontext nicht verfügbar.", "Automatischer Versand in eigene Kanäle ist auf dem geprüften Retailclient blockiert.",
        "Spieler gestorben.", "Diagnoseprotokoll gelöscht.", "Keine Raidgruppe.", "Keine eigene Gruppe.", "Keine Instanzgruppe.", "Keine Gildenzugehörigkeit.", "Kein Testempfänger eingestellt.", "Kein beigetretener Testkanal eingestellt.", "Keine Raidwarnungsberechtigung.",
    },
    esES={
        "El envío automático a hermandad se retiene temporalmente en el cliente Retail probado: hubo bloqueos sin restricciones activas de Chat/Map. Se conserva tu opción; los demás destinos siguen disponibles.",
        "Probar directamente las restricciones de Blizzard", "Desactivado: prueba las reglas normales del addon. Activado: realiza llamadas únicas a la API, incluso donde el envío normal se omite. Puede generar mensajes visibles y errores de protección. No elude restricciones. Espera a que el compañero esté listo antes del jefe.",
        "Preparación detenida: %s", "Versión de diagnóstico: %s", "Canales preparados: %d / %d",
        "El compañero usa otra versión de diagnóstico. Actualizad ambos addons.", "Receptor Starter: no permite verificar recepción de hermandad/oficiales.", "Solo eco propio; recepción del compañero sin confirmar.",
        "Sin prueba activa", "Buscando compañero", "Compañero encontrado; preparando canales", "Preparación en espera por restricciones de chat", "Compañero listo; esperando contexto", "Prueba en curso", "Prueba terminada", "Prueba cancelada",
        "Consulta el registro para más detalles.", "Comunicación protegida; sin reintento hasta recargar.", "Falló la comunicación del addon.", "La preparación caducó durante restricciones de chat.", "La preparación de canales no terminó a tiempo.", "Sin respuesta dentro del plazo.", "El compañero no ha activado la recepción.", "Protocolos de diagnóstico incompatibles.",
        "Envío automático a hermandad retenido por precaución.", "El canal causó un error de protección; sin reintento hasta recargar.", "Chat público automático no disponible aquí.", "Envío automático a canales personalizados bloqueado en Retail probado.",
        "Jugador muerto.", "Registro borrado.", "Sin banda.", "Sin grupo propio.", "Sin grupo de instancia.", "Sin hermandad.", "Sin destinatario de prueba.", "Sin canal de prueba unido.", "Sin permiso de aviso de banda.",
    },
    esMX={
        "El envío automático a hermandad se retiene temporalmente en el cliente Retail probado: hubo bloqueos sin restricciones activas de Chat/Map. Se conserva tu opción; los demás destinos siguen disponibles.",
        "Probar directamente las restricciones de Blizzard", "Desactivado: prueba las reglas normales del addon. Activado: realiza llamadas únicas a la API, incluso donde el envío normal se omite. Puede generar mensajes visibles y errores de protección. No elude restricciones. Espera a que el compañero esté listo antes del jefe.",
        "Preparación detenida: %s", "Versión de diagnóstico: %s", "Canales preparados: %d / %d",
        "El compañero usa otra versión de diagnóstico. Actualicen ambos addons.", "Receptor Starter: no permite verificar recepción de hermandad/oficiales.", "Solo eco propio; recepción del compañero sin confirmar.",
        "Sin prueba activa", "Buscando compañero", "Compañero encontrado; preparando canales", "Preparación en espera por restricciones de chat", "Compañero listo; esperando contexto", "Prueba en curso", "Prueba terminada", "Prueba cancelada",
        "Consulta el registro para más detalles.", "Comunicación protegida; sin reintento hasta recargar.", "Falló la comunicación del addon.", "La preparación caducó durante restricciones de chat.", "La preparación de canales no terminó a tiempo.", "Sin respuesta dentro del plazo.", "El compañero no ha activado la recepción.", "Protocolos de diagnóstico incompatibles.",
        "Envío automático a hermandad retenido por precaución.", "El canal causó un error de protección; sin reintento hasta recargar.", "Chat público automático no disponible aquí.", "Envío automático a canales personalizados bloqueado en Retail probado.",
        "Jugador muerto.", "Registro borrado.", "Sin banda.", "Sin grupo propio.", "Sin grupo de instancia.", "Sin hermandad.", "Sin destinatario de prueba.", "Sin canal de prueba unido.", "Sin permiso de aviso de banda.",
    },
    frFR={
        "L'envoi automatique de guilde est temporairement suspendu sur le client Retail testé : des blocages ont eu lieu sans restriction Chat/Map active. Votre option est conservée ; les autres destinations restent disponibles.",
        "Tester directement les restrictions Blizzard", "Désactivé : tester les règles normales. Activé : appels uniques à l'API, même dans les situations ignorées normalement. Messages visibles et erreurs de protection possibles. Aucune restriction contournée. Attendez que le partenaire soit prêt avant le boss.",
        "Préparation arrêtée : %s", "Version du diagnostic : %s", "Canaux préparés : %d / %d",
        "Le partenaire utilise une autre version du diagnostic. Mettez à jour les deux addons.", "Destinataire Starter : réception guilde/officiers invérifiable avec ce partenaire.", "Écho personnel uniquement ; réception du partenaire non confirmée.",
        "Aucun test actif", "Recherche du partenaire", "Partenaire trouvé ; préparation des canaux", "Préparation en attente de la fin des restrictions", "Partenaire prêt ; attente du contexte", "Test en cours", "Test terminé", "Test annulé",
        "Consultez le journal pour les détails.", "Communication protégée ; aucun nouvel essai avant rechargement.", "Échec de communication de l'addon.", "Préparation expirée pendant les restrictions de discussion.", "Préparation des canaux inachevée dans le délai.", "Aucune réponse dans le délai.", "Le partenaire n'a pas activé la réception.", "Protocoles de diagnostic incompatibles.",
        "Envoi automatique de guilde suspendu par précaution.", "Ce canal a causé une erreur de protection ; aucun nouvel essai avant rechargement.", "Discussion publique automatique indisponible ici.", "Envoi automatique aux canaux personnalisés bloqué sur le Retail testé.",
        "Personnage mort.", "Journal effacé.", "Aucun raid.", "Aucun groupe personnel.", "Aucun groupe d'instance.", "Aucune guilde.", "Aucun destinataire de test.", "Aucun canal de test rejoint.", "Aucune permission d'avertissement de raid.",
    },
    ptBR={
        "O envio automático à guilda está temporariamente suspenso no Retail testado: houve bloqueios sem restrições Chat/Map ativas. Sua opção é preservada; outros destinos continuam disponíveis.",
        "Testar diretamente as restrições da Blizzard", "Desligado: testa as regras normais. Ligado: chamadas únicas à API, inclusive onde o envio normal é ignorado. Mensagens visíveis e erros de proteção são possíveis. Nenhuma restrição é contornada. Aguarde o parceiro ficar pronto antes do chefe.",
        "Preparação interrompida: %s", "Versão do diagnóstico: %s", "Canais preparados: %d / %d",
        "O parceiro usa outra versão de diagnóstico. Atualize ambos os addons.", "Destinatário Starter: não permite confirmar recebimento de guilda/oficiais.", "Apenas eco próprio; recebimento pelo parceiro não confirmado.",
        "Nenhum teste ativo", "Buscando parceiro", "Parceiro encontrado; preparando canais", "Preparação aguardando fim das restrições", "Parceiro pronto; aguardando contexto", "Teste em execução", "Teste concluído", "Teste cancelado",
        "Veja os detalhes no registro.", "Comunicação protegida; sem nova tentativa até recarregar.", "Falha na comunicação do addon.", "Preparação expirou durante restrições de chat.", "Preparação dos canais não terminou no prazo.", "Sem resposta no prazo.", "O parceiro não ativou o recebimento.", "Protocolos de diagnóstico incompatíveis.",
        "Envio automático à guilda suspenso por precaução.", "Este canal causou erro de proteção; sem nova tentativa até recarregar.", "Chat público automático indisponível neste contexto.", "Envio automático a canais personalizados bloqueado no Retail testado.",
        "Jogador morreu.", "Registro apagado.", "Sem raide.", "Sem grupo próprio.", "Sem grupo de instância.", "Sem guilda.", "Sem destinatário de teste.", "Sem canal de teste conectado.", "Sem permissão de aviso de raide.",
    },
    ruRU={
        "Автоматическая отправка в гильдию временно приостановлена на проверенном Retail: блокировки возникали без активных ограничений Chat/Map. Настройка сохранена; остальные каналы доступны.",
        "Проверять ограничения Blizzard напрямую", "Выключено: обычные правила аддона. Включено: однократные вызовы API, включая обычно пропускаемые условия. Возможны видимые сообщения и ошибки защиты. Ограничения не обходятся. Дождитесь готовности партнёра перед боссом.",
        "Подготовка остановлена: %s", "Сборка диагностики: %s", "Подготовлено каналов: %d / %d",
        "У партнёра другая сборка диагностики. Обновите оба аддона.", "Получатель Starter: приём гильдии/офицеров проверить невозможно.", "Только собственное эхо; приём партнёром не подтверждён.",
        "Нет активного теста", "Поиск партнёра", "Партнёр найден; подготовка каналов", "Подготовка ожидает снятия ограничений чата", "Партнёр готов; ожидание условий", "Тест выполняется", "Тест завершён", "Тест отменён",
        "Подробности в журнале диагностики.", "Связь защищена; повторов до перезагрузки нет.", "Ошибка связи аддона.", "Подготовка истекла во время ограничений чата.", "Каналы не подготовлены в срок.", "Нет ответа в отведённое время.", "Партнёр не включил приём.", "Несовместимые протоколы диагностики.",
        "Автоматическая отправка в гильдию приостановлена для безопасности.", "Канал вызвал ошибку защиты; повторов до перезагрузки нет.", "Публичный автоматический чат здесь недоступен.", "Автоматическая отправка в свои каналы заблокирована на проверенном Retail.",
        "Персонаж погиб.", "Журнал очищен.", "Нет рейда.", "Нет своей группы.", "Нет группы подземелья.", "Нет гильдии.", "Нет тестового получателя.", "Нет подключённого тестового канала.", "Нет прав на предупреждение рейда.",
    },
    koKR={
        "테스트한 Retail에서는 Chat/Map 제한이 없어도 차단되어 자동 길드 전송을 일시 보류합니다. 길드 설정은 유지되며 다른 대상은 계속 사용할 수 있습니다.",
        "블리자드 제한 직접 테스트", "끄면 애드온의 일반 전송 규칙을 테스트합니다. 켜면 평소 건너뛰는 상황에서도 API를 한 번 호출합니다. 표시되는 메시지와 보호 오류가 발생할 수 있습니다. 제한을 우회하지 않습니다. 우두머리 전투 전에 상대가 준비될 때까지 기다리세요.",
        "상대 준비 중단: %s", "진단 빌드: %s", "준비된 채널: %d / %d",
        "상대의 진단 빌드가 다릅니다. 두 애드온을 업데이트하세요.", "Starter 수신자: 길드/관리자 수신을 확인할 수 없습니다.", "자신의 메시지만 표시됨; 상대 수신은 미확인입니다.",
        "활성 테스트 없음", "상대 찾는 중", "상대 확인; 채널 준비 중", "채팅 제한 해제를 기다리는 중", "상대 준비 완료; 테스트 상황 대기", "테스트 진행 중", "테스트 완료", "테스트 취소",
        "자세한 내용은 진단 기록을 확인하세요.", "애드온 통신 보호됨; 재시작 전 재시도 없음.", "애드온 통신 실패.", "채팅 제한 중 준비 시간이 만료되었습니다.", "채널 준비 제한 시간 초과.", "제한 시간 내 상대 응답 없음.", "상대가 수신을 켜지 않았습니다.", "진단 프로토콜 불일치.",
        "안전을 위해 자동 길드 전송을 보류합니다.", "이 채널에서 보호 오류 발생; 재시작 전 재시도 없음.", "이 상황에서는 자동 공개 채팅을 사용할 수 없습니다.", "테스트한 Retail에서 자동 사용자 채널 전송이 차단됩니다.",
        "플레이어 사망.", "진단 기록 삭제됨.", "공격대 없음.", "일반 파티 없음.", "인스턴스 그룹 없음.", "길드 없음.", "테스트 수신자 없음.", "참가한 테스트 채널 없음.", "공격대 경보 권한 없음.",
    },
    zhCN={
        "在测试的Retail客户端上，即使Chat/Map限制未激活也发生阻止，因此暂缓自动公会发送。公会选项保留，其他目标仍可用。",
        "直接测试暴雪限制", "关闭：测试插件正常发送规则。开启：在通常跳过的环境中也只调用一次API。可能产生可见消息和保护错误，不绕过限制。首领战前请等待伙伴准备完成。",
        "伙伴准备已停止：%s", "诊断版本：%s", "已准备频道：%d / %d",
        "伙伴诊断版本不同，请更新双方插件。", "Starter接收者：无法验证公会/官员接收。", "仅有自身回显，伙伴接收未确认。",
        "无活动测试", "正在寻找伙伴", "已找到伙伴，正在准备频道", "准备正在等待聊天限制解除", "伙伴已准备，等待测试环境", "测试进行中", "测试已完成", "测试已取消",
        "详情请查看诊断记录。", "插件通信受保护，重载前不重试。", "插件通信失败。", "聊天限制期间准备超时。", "频道准备未在时限内完成。", "时限内未收到伙伴响应。", "伙伴未开启接收。", "诊断协议不兼容。",
        "为安全起见暂缓自动公会发送。", "此频道曾产生保护错误，重载前不重试。", "当前环境不允许自动公共聊天。", "测试的Retail客户端阻止自动自定义频道发送。",
        "玩家已死亡。", "诊断记录已清除。", "没有团队。", "没有普通队伍。", "没有副本队伍。", "没有公会。", "未设置测试接收者。", "未设置已加入的测试频道。", "没有团队警报权限。",
    },
    zhTW={
        "在測試的Retail用戶端上，即使Chat/Map限制未啟用也發生阻止，因此暫緩自動公會傳送。公會選項保留，其他目標仍可用。",
        "直接測試暴雪限制", "關閉：測試插件正常傳送規則。開啟：在通常略過的環境中也只呼叫一次API。可能產生可見訊息和保護錯誤，不繞過限制。首領戰前請等待夥伴準備完成。",
        "夥伴準備已停止：%s", "診斷版本：%s", "已準備頻道：%d / %d",
        "夥伴診斷版本不同，請更新雙方插件。", "Starter收件人：無法驗證公會/幹部接收。", "僅有自身回顯，夥伴接收未確認。",
        "無活動測試", "正在尋找夥伴", "已找到夥伴，正在準備頻道", "準備正在等待聊天限制解除", "夥伴已準備，等待測試環境", "測試進行中", "測試已完成", "測試已取消",
        "詳情請查看診斷記錄。", "插件通訊受保護，重載前不重試。", "插件通訊失敗。", "聊天限制期間準備逾時。", "頻道準備未在時限內完成。", "時限內未收到夥伴回應。", "夥伴未開啟接收。", "診斷協定不相容。",
        "為安全起見暫緩自動公會傳送。", "此頻道曾產生保護錯誤，重載前不重試。", "目前環境不允許自動公共聊天。", "測試的Retail用戶端阻止自動自訂頻道傳送。",
        "玩家已死亡。", "診斷記錄已清除。", "沒有團隊。", "沒有一般隊伍。", "沒有副本隊伍。", "沒有公會。", "未設定測試收件人。", "未設定已加入的測試頻道。", "沒有團隊警報權限。",
    },
}
for locale,values in pairs(followup) do
    for index,key in ipairs(followupKeys) do QuestAnnounce_L[locale][key]=values[index] end
    QuestAnnounce_L[locale]["Diagnostic command help"]=QuestAnnounce_L[locale]["Diagnostic command help"]
        .. "\n/qa diag mode normal|probe"
end
