-- DE: Partnerdiagnose in allen unterstützten Sprachen; Protokollwörter bleiben sprachunabhängig.
-- EN: Peer diagnostics in every supported locale; protocol tokens remain language-independent.
local keys={
    "Diagnostic partner", "Diagnostic partner help", "Diagnostic receive", "Diagnostic receive help",
    "Diagnostic partner required", "Diagnostic partner unavailable", "Diagnostic partner ready",
    "Diagnostic channels", "Diagnostic channels help", "Diagnostic channels required",
    "Diagnostic results", "Diagnostic results help", "Diagnostic confirm", "Diagnostic confirm help",
    "Diagnostic receiver on", "Diagnostic receiver off", "Diagnostic select result",
    "Diagnostic status waiting", "Diagnostic status pending", "Diagnostic status received", "Diagnostic status manual",
    "Diagnostic status skipped", "Diagnostic status blocked", "Diagnostic status error", "Diagnostic status unconfirmed",
    "Diagnostic status cancelled", "Diagnostic status local",
}
local texts={
    enUS={
        "Test partner (Name-Realm)", "Both players choose each other here. The recipient enables receiving. Leave blank for manual tests. In paired tests, WHISPER targets this partner. Normal quest settings stay unchanged.",
        "Receive partner tests", "Explicitly accept diagnostic tests only from the selected partner. Confirms actual chat events, not reading or window visibility. Test messages remain visible; acknowledgements use hidden addon communication.",
        "Choose a valid other character as test partner first.", "Partner connection unavailable or timed out. Enable receiving on the partner. No paired chat probes were sent; manual tests remain available.",
        "Partner ready. Waiting for the selected test context.", "Channels to test", "Select only the channels you need. Missing membership or targets are skipped. Both players need access; local chat also needs range. Start boss tests before the encounter to prepare the connection.",
        "Select at least one diagnostic channel.", "Recent results", "Partner receipt means a chat event reached the other client. Missing acknowledgement stays unconfirmed. Blocked replies are buffered for up to 10 minutes, including reload. Both clients keep receipt evidence; /reload saves the log.",
        "Confirm selected result", "For local displays or a partner without automatic acknowledgement: select a test below and confirm only after observing the display or checking with the recipient. No test-ID typing needed.",
        "Partner receiver enabled", "Partner receiver disabled", "Select a test for manual confirmation",
        "Waiting", "Confirmation pending", "Received by partner", "Manually confirmed", "Skipped", "Blizzard blocked", "API error", "Unconfirmed", "Cancelled", "Check local display",
    },
    deDE={
        "Testpartner (Name-Realm)", "Beide Spieler tragen sich hier gegenseitig ein. Der Empfänger aktiviert den Empfang. Für manuelle Tests leer lassen. WHISPER geht bei Partnertests an diesen Spieler. Normale Questoptionen bleiben erhalten.",
        "Partnertests empfangen", "Nimmt Diagnosetests ausdrücklich nur vom gewählten Partner an. Bestätigt tatsächliche Chatereignisse, nicht Lesen oder Sichtbarkeit im Fenster. Testnachrichten bleiben sichtbar; Rückmeldungen nutzen unsichtbare Addon-Kommunikation.",
        "Wähle zuerst einen gültigen anderen Charakter als Testpartner.", "Partnerverbindung fehlt oder ist abgelaufen. Beim Partner den Empfang aktivieren. Keine Partner-Chattests gesendet; manuelle Tests bleiben verfügbar.",
        "Partner bereit. Warte auf den gewählten Testzustand.", "Zu testende Kanäle", "Wähle nur benötigte Kanäle. Fehlende Zugehörigkeit oder Ziele werden übersprungen. Beide brauchen Zugang; lokaler Chat auch Reichweite. Bosstests vor dem Encounter starten, damit die Verbindung vorbereitet wird.",
        "Wähle mindestens einen Diagnosekanal.", "Letzte Ergebnisse", "Partnerempfang bedeutet ein Chatereignis beim anderen Client. Fehlende Rückmeldung bleibt unbestätigt. Gesperrte Rückmeldungen warten bis zu 10 Minuten, auch über Reload. Beide Clients speichern Empfangsbelege; /reload sichert das Log.",
        "Gewähltes Ergebnis bestätigen", "Für lokale Anzeigen oder Partner ohne automatische Rückmeldung: unten einen Test wählen und erst nach Sichtprüfung oder Rückfrage beim Empfänger bestätigen. Kein Abtippen von Test-IDs nötig.",
        "Partnerempfang aktiviert", "Partnerempfang deaktiviert", "Test zur manuellen Bestätigung wählen",
        "Wartet", "Bestätigung ausstehend", "Beim Partner empfangen", "Manuell bestätigt", "Übersprungen", "Von Blizzard blockiert", "API-Fehler", "Unbestätigt", "Abgebrochen", "Lokale Anzeige prüfen",
    },
    esES={
        "Compañero (Nombre-Reino)", "Ambos jugadores se seleccionan mutuamente. El destinatario activa la recepción. Déjalo vacío para pruebas manuales. WHISPER se dirige al compañero. No cambia los anuncios normales.",
        "Recibir pruebas del compañero", "Acepta pruebas solo del compañero elegido. Confirma eventos de chat, no la lectura ni la visibilidad. Las pruebas son visibles; las confirmaciones usan comunicación oculta del addon.",
        "Selecciona primero otro personaje válido.", "Conexión no disponible o caducada. Activa la recepción en el compañero. No se enviaron pruebas de chat emparejadas; siguen disponibles las manuales.",
        "Compañero listo. Esperando el contexto elegido.", "Canales de prueba", "Selecciona los canales necesarios. Se omiten los que no tengan requisitos. Ambos necesitan acceso y alcance para el chat local. Inicia pruebas de jefe antes del encuentro.",
        "Selecciona al menos un canal.", "Resultados recientes", "Recepción indica un evento de chat en el otro cliente. Sin confirmación queda sin verificar. Respuestas bloqueadas esperan hasta 10 minutos, incluso tras /reload. Ambos guardan evidencias; /reload guarda el registro.",
        "Confirmar resultado elegido", "Para avisos locales o recepción manual: selecciona una prueba y confirma tras verla o consultar al destinatario. No necesitas escribir IDs.",
        "Recepción activada", "Recepción desactivada", "Selecciona una prueba para confirmar",
        "Esperando", "Confirmación pendiente", "Recibido por compañero", "Confirmado manualmente", "Omitido", "Bloqueado por Blizzard", "Error de API", "Sin confirmar", "Cancelado", "Comprobar aviso local",
    },
    esMX={
        "Compañero (Nombre-Reino)", "Ambos jugadores se seleccionan mutuamente. El destinatario activa la recepción. Déjalo vacío para pruebas manuales. WHISPER va al compañero. No cambia los anuncios normales.",
        "Recibir pruebas del compañero", "Acepta pruebas solo del compañero seleccionado. Confirma eventos de chat, no lectura ni visibilidad. Las pruebas son visibles; las confirmaciones usan comunicación oculta del addon.",
        "Primero selecciona otro personaje válido.", "Conexión no disponible o vencida. Activa la recepción en el compañero. No se enviaron pruebas de chat emparejadas; puedes usar pruebas manuales.",
        "Compañero listo. Esperando el contexto seleccionado.", "Canales de prueba", "Selecciona los canales necesarios. Se omiten los que no cumplen los requisitos. Ambos necesitan acceso y alcance para el chat local. Inicia pruebas de jefe antes del encuentro.",
        "Selecciona al menos un canal.", "Resultados recientes", "Recepción indica un evento de chat en el otro cliente. Sin confirmación queda sin verificar. Respuestas bloqueadas esperan hasta 10 minutos, incluso tras /reload. Ambos guardan evidencias; /reload guarda el registro.",
        "Confirmar resultado seleccionado", "Para avisos locales o recepción manual: selecciona una prueba y confirma después de verla o preguntar al destinatario. No necesitas escribir IDs.",
        "Recepción activada", "Recepción desactivada", "Selecciona una prueba para confirmar",
        "Esperando", "Confirmación pendiente", "Recibido por compañero", "Confirmado manualmente", "Omitido", "Bloqueado por Blizzard", "Error de API", "Sin confirmar", "Cancelado", "Revisar aviso local",
    },
    frFR={
        "Partenaire (Nom-Royaume)", "Les deux joueurs se choisissent mutuellement. Le destinataire active la réception. Laissez vide pour les tests manuels. WHISPER vise ce partenaire. Les annonces normales restent inchangées.",
        "Recevoir les tests du partenaire", "Accepte uniquement le partenaire choisi. Confirme des événements de discussion, pas la lecture ni l'affichage. Les tests restent visibles ; les confirmations utilisent la communication cachée de l'addon.",
        "Choisissez d'abord un autre personnage valide.", "Connexion indisponible ou expirée. Activez la réception chez le partenaire. Aucun test de discussion apparié envoyé ; les tests manuels restent disponibles.",
        "Partenaire prêt. En attente du contexte choisi.", "Canaux à tester", "Choisissez les canaux nécessaires. Les prérequis manquants sont ignorés. Les deux joueurs doivent avoir accès et être à portée pour la discussion locale. Lancez les tests de boss avant le combat.",
        "Choisissez au moins un canal.", "Résultats récents", "La réception signifie un événement chez l'autre client. Sans confirmation, le résultat reste indéterminé. Les réponses bloquées attendent 10 minutes maximum, même après /reload. Les deux clients gardent des preuves ; /reload sauvegarde le journal.",
        "Confirmer le résultat choisi", "Pour l'affichage local ou la réception manuelle : choisissez un test et confirmez après vérification visuelle ou auprès du destinataire. Aucun identifiant à saisir.",
        "Réception activée", "Réception désactivée", "Choisir un test à confirmer",
        "En attente", "Confirmation en attente", "Reçu par le partenaire", "Confirmé manuellement", "Ignoré", "Bloqué par Blizzard", "Erreur API", "Non confirmé", "Annulé", "Vérifier l'affichage local",
    },
    ptBR={
        "Parceiro (Nome-Reino)", "Os dois jogadores selecionam um ao outro. O destinatário ativa a recepção. Deixe vazio para testes manuais. WHISPER vai para esse parceiro. Os anúncios normais não mudam.",
        "Receber testes do parceiro", "Aceita testes apenas do parceiro escolhido. Confirma eventos de bate-papo, não leitura ou visibilidade. Testes são visíveis; confirmações usam comunicação oculta do addon.",
        "Primeiro selecione outro personagem válido.", "Conexão indisponível ou expirada. Ative a recepção no parceiro. Nenhum teste de bate-papo em par foi enviado; testes manuais continuam disponíveis.",
        "Parceiro pronto. Aguardando o contexto escolhido.", "Canais para testar", "Escolha os canais necessários. Requisitos ausentes são ignorados. Ambos precisam de acesso e alcance no bate-papo local. Inicie testes de chefe antes do encontro.",
        "Escolha pelo menos um canal.", "Resultados recentes", "Recepção significa um evento no outro cliente. Sem confirmação, fica não confirmado. Respostas bloqueadas aguardam até 10 minutos, mesmo após /reload. Ambos guardam evidências; /reload salva o registro.",
        "Confirmar resultado escolhido", "Para avisos locais ou recepção manual: escolha um teste e confirme depois de ver o aviso ou consultar o destinatário. Não precisa digitar IDs.",
        "Recepção ativada", "Recepção desativada", "Escolha um teste para confirmar",
        "Aguardando", "Confirmação pendente", "Recebido pelo parceiro", "Confirmado manualmente", "Ignorado", "Bloqueado pela Blizzard", "Erro de API", "Não confirmado", "Cancelado", "Verificar aviso local",
    },
    ruRU={
        "Партнёр (Имя-Сервер)", "Оба игрока выбирают друг друга. Получатель включает приём. Оставьте пустым для ручных тестов. WHISPER отправляется партнёру. Обычные объявления не меняются.",
        "Принимать тесты партнёра", "Принимает тесты только выбранного партнёра. Подтверждает событие чата, а не прочтение или отображение. Тесты видимы; подтверждения используют скрытый канал аддона.",
        "Сначала выберите другого персонажа.", "Связь недоступна или время ожидания истекло. Включите приём у партнёра. Парные сообщения не отправлены; ручные тесты доступны.",
        "Партнёр готов. Ожидание выбранных условий.", "Каналы для теста", "Выберите нужные каналы. Без доступа или цели тест пропускается. Оба игрока должны иметь доступ, а для местного чата быть рядом. Запустите тест босса до боя.",
        "Выберите хотя бы один канал.", "Последние результаты", "Приём означает событие на другом клиенте. Без ответа результат не подтверждён. Заблокированные ответы ждут до 10 минут, включая /reload. Оба клиента хранят доказательства; /reload сохраняет журнал.",
        "Подтвердить выбранный результат", "Для местных окон или ручного приёма: выберите тест и подтвердите после проверки отображения или ответа получателя. Вводить ID не нужно.",
        "Приём включён", "Приём выключен", "Выберите тест для подтверждения",
        "Ожидание", "Ожидание подтверждения", "Получено партнёром", "Подтверждено вручную", "Пропущено", "Заблокировано Blizzard", "Ошибка API", "Не подтверждено", "Отменено", "Проверьте местное окно",
    },
    koKR={
        "테스트 상대 (이름-서버)", "두 플레이어가 서로를 선택합니다. 수신자는 수신을 켭니다. 수동 테스트는 비워 두세요. WHISPER는 이 상대에게 전송됩니다. 일반 알림 설정은 바뀌지 않습니다.",
        "상대 테스트 수신", "선택한 상대의 테스트만 받습니다. 읽음이나 창 표시가 아닌 실제 대화 이벤트를 확인합니다. 테스트 메시지는 보이며 확인은 숨겨진 애드온 통신을 사용합니다.",
        "먼저 다른 유효한 캐릭터를 선택하세요.", "상대 연결을 사용할 수 없거나 시간이 초과되었습니다. 상대의 수신을 켜세요. 연결 테스트 메시지는 전송되지 않았으며 수동 테스트는 가능합니다.",
        "상대가 준비되었습니다. 선택한 상황을 기다립니다.", "테스트 채널", "필요한 채널만 선택하세요. 조건이 부족하면 건너뜁니다. 양쪽 모두 접근 권한이 필요하며 지역 대화는 거리도 필요합니다. 우두머리 전투 전에 테스트를 시작하세요.",
        "채널을 하나 이상 선택하세요.", "최근 결과", "수신은 상대 클라이언트의 대화 이벤트를 뜻합니다. 응답이 없으면 미확인입니다. 차단된 응답은 /reload 후에도 최대 10분 기다립니다. 양쪽이 증거를 기록하며 /reload로 저장합니다.",
        "선택한 결과 확인", "개인 표시나 수동 수신 확인: 테스트를 선택하고 직접 표시를 보거나 수신자에게 확인한 뒤 누르세요. ID 입력은 필요 없습니다.",
        "상대 수신 켜짐", "상대 수신 꺼짐", "수동 확인할 테스트 선택",
        "대기", "확인 대기", "상대 수신 완료", "수동 확인 완료", "건너뜀", "블리자드 차단", "API 오류", "미확인", "취소됨", "개인 표시 확인 필요",
    },
    zhCN={
        "测试伙伴（名字-服务器）", "双方互相选择对方。收件人开启接收。手动测试请留空。WHISPER发送给此伙伴，不改变普通通告设置。",
        "接收伙伴测试", "只接受所选伙伴的测试。确认实际聊天事件，不代表已读或窗口显示。测试消息可见，确认使用隐藏的插件通信。",
        "请先选择一个有效的其他角色。", "伙伴连接不可用或超时。请在伙伴端开启接收。未发送配对聊天测试，仍可使用手动测试。",
        "伙伴已准备，等待所选测试状态。", "测试频道", "只选择需要的频道。缺少条件或目标时跳过。双方需有权限，本地聊天还需在范围内。首领测试应在战斗前启动以准备连接。",
        "请至少选择一个频道。", "最近结果", "伙伴接收表示对方客户端收到聊天事件。无回复保持未确认。被限制的回复最多等待10分钟，重载后仍保留。双方保存接收证据，/reload保存记录。",
        "确认所选结果", "本地显示或手动接收：选择测试，仅在看到显示或询问收件人后确认。无需输入测试ID。",
        "伙伴接收已开启", "伙伴接收已关闭", "选择需手动确认的测试",
        "等待中", "等待确认", "伙伴已接收", "已手动确认", "已跳过", "被暴雪阻止", "API错误", "未确认", "已取消", "请检查本地显示",
    },
    zhTW={
        "測試夥伴（名字-伺服器）", "雙方互相選擇對方。收件人開啟接收。手動測試請留空。WHISPER傳送給此夥伴，不改變一般通告設定。",
        "接收夥伴測試", "僅接受所選夥伴的測試。確認實際聊天事件，不代表已讀或視窗顯示。測試訊息可見，確認使用隱藏的插件通訊。",
        "請先選擇有效的其他角色。", "夥伴連線無法使用或逾時。請在夥伴端開啟接收。未傳送配對聊天測試，仍可使用手動測試。",
        "夥伴已準備，等待所選測試狀態。", "測試頻道", "僅選擇需要的頻道。缺少條件或目標時略過。雙方需有權限，本地聊天還需在範圍內。首領測試應在戰鬥前啟動以準備連線。",
        "請至少選擇一個頻道。", "最近結果", "夥伴接收表示對方用戶端收到聊天事件。無回覆保持未確認。受限制的回覆最多等待10分鐘，重載後仍保留。雙方保存接收證據，/reload儲存記錄。",
        "確認所選結果", "本地顯示或手動接收：選擇測試，僅在看到顯示或詢問收件人後確認。無需輸入測試ID。",
        "夥伴接收已開啟", "夥伴接收已關閉", "選擇需手動確認的測試",
        "等待中", "等待確認", "夥伴已接收", "已手動確認", "已略過", "被暴雪阻止", "API錯誤", "未確認", "已取消", "請檢查本地顯示",
    },
}
for locale, values in pairs(texts) do
    for index, key in ipairs(keys) do QuestAnnounce_L[locale][key]=values[index] end
    QuestAnnounce_L[locale]["Diagnostic command help"]=QuestAnnounce_L[locale]["Diagnostic command help"]
        .. "\n/qa diag partner Name-Realm\n/qa diag receive on|off\n/qa diag channels all|GUILD OFFICER"
end
local clearHelp={
    enUS="Stop active tests and clear log entries, results and pending receipts. Preserve profiles, diagnostic targets and recording settings.",
    deDE="Beendet aktive Tests und löscht Logeinträge, Ergebnisse und wartende Empfangsbestätigungen. Profile, Diagnoseziele und Aufzeichnungseinstellungen bleiben erhalten.",
    esES="Detiene las pruebas y borra entradas, resultados y confirmaciones pendientes. Conserva perfiles, destinos y configuración de registro.",
    esMX="Detiene las pruebas y borra registros, resultados y confirmaciones pendientes. Conserva perfiles, destinos y configuración de registro.",
    frFR="Arrête les tests et efface le journal, les résultats et les confirmations en attente. Conserve les profils, les destinations et les réglages d'enregistrement.",
    ptBR="Para os testes e apaga registros, resultados e confirmações pendentes. Preserva perfis, destinos e configurações de registro.",
    ruRU="Останавливает тесты и очищает журнал, результаты и ожидающие подтверждения. Сохраняет профили, цели и настройки записи.",
    koKR="테스트를 중지하고 기록, 결과 및 대기 중인 확인을 삭제합니다. 프로필, 진단 대상 및 기록 설정은 유지합니다.",
    zhCN="停止测试并清除日志、结果和待发送的接收确认。保留配置、诊断目标和记录设置。",
    zhTW="停止測試並清除日誌、結果及待傳送的接收確認。保留設定檔、診斷目標及記錄設定。",
}
for locale, text in pairs(clearHelp) do QuestAnnounce_L[locale]["Clear diagnostic log help"]=text end
